// PRESERVE EVERYTHING - Original Variant styles, unchanged
export const customStyles = {
  root: {
    '--bg-mint': '#EAF8F5',
    '--ink': '#251720',
    '--ink-light': '#5A4C55',
    '--emerald': '#00D27F',
    '--gold': '#FFD600',
    '--surface': '#FFFFFF',
  },
  body: {
    background: 'linear-gradient(135deg, #F2FDFB 0%, #EAF8F5 100%)',
    color: '#251720',
    fontFamily: "'DM Sans', sans-serif",
    lineHeight: '1.5',
    minHeight: '100vh',
    overflowX: 'hidden',
    backgroundImage: 'radial-gradient(#251720 1px, transparent 1px)',
    backgroundSize: '32px 32px',
    backgroundPosition: '-1px -1px',
  },
  systemContainer: {
    maxWidth: '1440px',
    margin: '0 auto',
    borderLeft: '3px solid #251720',
    borderRight: '3px solid #251720',
    background: 'rgba(255,255,255,0.4)',
    backdropFilter: 'blur(10px)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '24px 32px',
    borderBottom: '3px solid #251720',
    background: '#FFFFFF',
  },
  logo: {
    fontFamily: "'Epilogue', sans-serif",
    fontSize: '2rem',
    fontWeight: 900,
    letterSpacing: '-0.05em',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    color: '#251720',
    textDecoration: 'none',
  },
  logoNode: {
    width: '24px',
    height: '24px',
    background: '#FFD600',
    border: '3px solid #251720',
    borderRadius: '50%',
    position: 'relative',
  },
  navLinks: {
    display: 'flex',
    gap: '32px',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '0.85rem',
    fontWeight: 700,
  },
  navLink: {
    color: '#251720',
    textDecoration: 'none',
  },
  hero: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    borderBottom: '3px solid #251720',
  },
  heroContent: {
    padding: '80px 64px',
    borderRight: '3px solid #251720',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  heroVisual: {
    background: '#EAF8F5',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px',
  },
  monoLabel: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '0.75rem',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    color: '#5A4C55',
    display: 'block',
    marginBottom: '0.5rem',
  },
  pill: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '4px 12px',
    borderRadius: '999px',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '0.7rem',
    fontWeight: 700,
    border: '2px solid #251720',
    background: '#FFFFFF',
    textTransform: 'uppercase',
  },
  pillActive: {
    background: '#00D27F',
  },
  h1: {
    fontFamily: "'Epilogue', sans-serif",
    textTransform: 'uppercase',
    lineHeight: '1.05',
    letterSpacing: '-0.02em',
    fontSize: 'clamp(3rem, 6vw, 5.5rem)',
    marginBottom: '24px',
  },
  subtitle: {
    fontSize: '1.25rem',
    color: '#5A4C55',
    maxWidth: '480px',
    marginBottom: '48px',
  },
  heroCtas: {
    display: 'flex',
    gap: '24px',
    flexWrap: 'wrap',
  },
  btn: {
    display: 'inline-flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '16px 32px',
    fontFamily: "'Epilogue', sans-serif",
    fontSize: '1.1rem',
    fontWeight: 900,
    textTransform: 'uppercase',
    color: '#251720',
    background: '#FFFFFF',
    border: '3px solid #251720',
    cursor: 'pointer',
    textDecoration: 'none',
    transition: 'all 0.1s ease',
    boxShadow: '6px 6px 0px #251720',
  },
  btnPrimary: {
    background: '#00D27F',
  },
  btnSecondary: {
    background: '#FFD600',
  },
  btnSmall: {
    alignSelf: 'flex-start',
    padding: '12px 24px',
    fontSize: '0.9rem',
    boxShadow: '6px 6px 0px #251720',
  },
  explanation: {
    display: 'grid',
    gridTemplateColumns: '300px 1fr',
    borderBottom: '3px solid #251720',
  },
  explHeader: {
    padding: '64px',
    borderRight: '3px solid #251720',
    background: '#251720',
    color: '#FFFFFF',
  },
  explHeaderH2: {
    fontFamily: "'Epilogue', sans-serif",
    textTransform: 'uppercase',
    lineHeight: '1.05',
    letterSpacing: '-0.02em',
    color: '#FFFFFF',
    fontSize: '3rem',
  },
  explContent: {
    padding: '64px',
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: '32px',
    background: '#FFFFFF',
  },
  explParagraph: {
    fontSize: '1.5rem',
    lineHeight: '1.6',
    letterSpacing: '-0.01em',
    maxWidth: '800px',
  },
  mechanics: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    borderBottom: '3px solid #251720',
  },
  mechCard: {
    padding: '48px',
    borderRight: '3px solid #251720',
    background: '#FFFFFF',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
  },
  mechCardLast: {
    borderRight: 'none',
  },
  mechIcon: {
    width: '64px',
    height: '64px',
    border: '3px solid #251720',
    borderRadius: '16px',
    marginBottom: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '3px 3px 0px #251720',
  },
  mechH3: {
    fontFamily: "'Epilogue', sans-serif",
    textTransform: 'uppercase',
    lineHeight: '1.05',
    letterSpacing: '-0.02em',
    fontSize: '2rem',
    marginBottom: '16px',
  },
  mechP: {
    color: '#5A4C55',
    marginBottom: '32px',
    flexGrow: 1,
  },
  statsSection: {
    padding: '64px',
    background: '#FFFFFF',
    borderBottom: '3px solid #251720',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '32px',
  },
  statCard: {
    padding: '32px',
    border: '3px solid #251720',
    background: '#EAF8F5',
    boxShadow: '3px 3px 0px #251720',
  },
  statNumber: {
    fontFamily: "'Epilogue', sans-serif",
    fontSize: '3rem',
    fontWeight: 900,
    lineHeight: '1',
    marginBottom: '8px',
  },
  statLabel: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '0.75rem',
    textTransform: 'uppercase',
    color: '#5A4C55',
  },
  venue: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    borderBottom: '3px solid #251720',
    background: '#FFFFFF',
  },
  venueInfo: {
    padding: '64px',
    borderRight: '3px solid #251720',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  venueH2: {
    fontFamily: "'Epilogue', sans-serif",
    textTransform: 'uppercase',
    lineHeight: '1.05',
    letterSpacing: '-0.02em',
    fontSize: '4rem',
    marginBottom: '16px',
  },
  venueMeta: {
    display: 'flex',
    gap: '16px',
    marginBottom: '32px',
    flexWrap: 'wrap',
  },
  venueImageContainer: {
    position: 'relative',
    minHeight: '500px',
  },
  venueImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    position: 'absolute',
    inset: 0,
    filter: 'contrast(1.1) saturate(0.8)',
  },
  hudOverlay: {
    position: 'absolute',
    bottom: '24px',
    right: '24px',
    background: '#FFFFFF',
    border: '3px solid #251720',
    padding: '16px',
    boxShadow: '3px 3px 0px #251720',
    zIndex: 10,
  },
  footerCapture: {
    padding: '120px 64px',
    background: '#251720',
    color: '#FFFFFF',
    textAlign: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  footerH2: {
    fontFamily: "'Epilogue', sans-serif",
    textTransform: 'uppercase',
    lineHeight: '1.05',
    letterSpacing: '-0.02em',
    fontSize: '4rem',
    color: '#FFFFFF',
    marginBottom: '48px',
    position: 'relative',
    zIndex: 2,
  },
  captureForm: {
    display: 'flex',
    maxWidth: '600px',
    margin: '0 auto',
    position: 'relative',
    zIndex: 2,
  },
  captureInput: {
    flexGrow: 1,
    padding: '24px 32px',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '1.1rem',
    border: '3px solid #00D27F',
    background: '#251720',
    color: '#FFFFFF',
    outline: 'none',
  },
  footerGrid: {
    position: 'absolute',
    inset: 0,
    backgroundImage: 'linear-gradient(rgba(255,255,255,0.05) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.05) 1px, transparent 1px)',
    backgroundSize: '40px 40px',
    zIndex: 1,
  },
};
